name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies for requirements and testing
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          pip install pylint pytest pytest-cov

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') || true  # Aggiunto "|| true" per evitare errori non fatali

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov  # Assicurati che pytest sia installato
          pytest --cov src /home/runner/work/RistoBOT/RistoBOT/test/
